apiVersion: v1
kind: Service
metadata:
  name: python-sample-service
spec:
  # Selector chọn các Pod có nhãn này để chuyển tiếp traffic
  selector:
    app: python-sample-app
  
  # Loại Service, chọn một trong các loại sau:
  # - ClusterIP (mặc định): Chỉ truy cập được trong cụm.
  # - NodePort: Mở cổng trên mỗi Node (cổng bên ngoài: 30000-32767).
  # - LoadBalancer: Cung cấp IP công cộng (nếu môi trường hỗ trợ).
  type: ClusterIP
  
  ports:
    - protocol: TCP
      # Cổng mà Service lắng nghe (cổng bên ngoài)
      port: 80 
      # Cổng mà ứng dụng bên trong container đang chạy
      targetPort: 5001
